"""Generate BJJ-VQA questions from a YouTube URL using Gemini via OpenRouter."""

import json
import os
import uuid
from pathlib import Path
from urllib.parse import parse_qs, urlparse

import ffmpeg
import instructor
import yt_dlp
from openai import OpenAI
from pydantic import BaseModel, Field

from bjj_vqa.schema import (
    Answer,
    Category,
    ExperienceLevel,
    SampleRecord,
    Source,
    Subject,
    get_data_dir,
)

_MODEL = "google/gemini-flash-latest"


def _get_client() -> instructor.Instructor:
    """Create an instructor-wrapped OpenAI client for OpenRouter."""
    base = OpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=os.environ["OPENROUTER_API_KEY"],
    )
    return instructor.from_openai(base)


def _load_prompt() -> str:
    """Load the generation prompt from prompt.md."""
    prompt_path = Path(__file__).parent / "prompt.md"
    return prompt_path.read_text()


class GeneratedQuestion(BaseModel):
    """Single question generated by Gemini."""

    question: str
    choices: list[str] = Field(min_length=2, max_length=4)
    answer: Answer
    experience_level: ExperienceLevel
    category: Category
    subject: Subject
    source: str
    stem_format: str  # "completion" | "classification"
    timestamp: int  # required, no default


class GeneratedQuestions(BaseModel):
    """Wrapper for a list of generated questions."""

    questions: list[GeneratedQuestion]


def generate_questions(youtube_url: str) -> list[GeneratedQuestion]:
    """Call Gemini via OpenRouter to generate questions from a YouTube URL.

    Returns a list of GeneratedQuestion objects (validated by instructor).
    """
    client = _get_client()
    prompt = _load_prompt()

    result = client.chat.completions.create(  # ty: ignore[no-matching-overload]
        model=_MODEL,
        messages=[
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": prompt},
                    {"type": "video_url", "video_url": {"url": youtube_url}},
                ],
            },
        ],
        temperature=0.3,
        max_tokens=8000,
        response_model=GeneratedQuestions,
    )

    return result.questions


def _get_video_info(youtube_url: str) -> dict:
    """Get video metadata via yt-dlp Python API."""
    ydl_opts = {
        "quiet": True,
        "no_warnings": True,
        "extract_flat": False,
    }
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        return ydl.extract_info(youtube_url, download=False)


def _get_stream_url(youtube_url: str) -> str:
    """Get direct stream URL via yt-dlp Python API."""
    ydl_opts = {
        "quiet": True,
        "no_warnings": True,
        "format": "best[height<=720]",
        "extract_flat": False,
    }
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        return ydl.extract_info(youtube_url, download=False)["url"]


def _detect_license(video_info: dict) -> str:
    """Auto-detect license type from yt-dlp info dict."""
    license_val = video_info.get("license")
    if license_val == "Creative Commons Attribution license (reuse allowed)":
        return "cc_by"
    return "permissioned"


def _extract_frame(stream_url: str, timestamp: int, output_path: Path) -> None:
    """Extract a single frame at the given timestamp using ffmpeg-python."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    (
        ffmpeg.input(stream_url, ss=timestamp)
        .output(str(output_path), vframes=1, q=2)
        .overwrite_output()
        .run(capture_stdout=True, capture_stderr=True)
    )


def _youtube_video_id(url: str) -> str | None:
    """Extract YouTube video ID from a URL, or None if not parseable."""
    parsed = urlparse(url)
    qs = parse_qs(parsed.query)
    ids = qs.get("v", [])
    return ids[0] if ids else None


def run(youtube_url: str) -> list[SampleRecord]:
    """Full generate pipeline: call Gemini, extract frames, append to samples.json.

    Returns the list of newly generated SampleRecord objects.
    """
    # Get video info for license detection and metadata
    video_info = _get_video_info(youtube_url)
    stream_url = _get_stream_url(youtube_url)
    license_type = _detect_license(video_info)

    # Generate questions via instructor (validated Pydantic)
    questions = generate_questions(youtube_url)
    data_dir = get_data_dir()
    images_dir = data_dir / "images"
    images_dir.mkdir(parents=True, exist_ok=True)

    records: list[SampleRecord] = []
    for q in questions:
        image_name = f"{uuid.uuid4().hex[:8]}.jpg"
        image_path = images_dir / image_name

        _extract_frame(stream_url, q.timestamp, image_path)

        record = SampleRecord(
            id=uuid.uuid4().hex[:8],
            image=f"images/{image_name}",
            question=q.question,
            choices=q.choices,
            answer=q.answer,
            experience_level=q.experience_level,
            category=q.category,
            subject=q.subject,
            source=q.source,
            timestamp=q.timestamp,
        )
        records.append(record)

    # Append to samples.json
    samples_path = data_dir / "samples.json"
    existing: list[dict] = []
    if samples_path.exists():
        existing = json.loads(samples_path.read_text())
    existing.extend([r.model_dump() for r in records])
    samples_path.write_text(json.dumps(existing, indent=2))

    # Update sources/registry.jsonl with new Source entry
    registry_path = data_dir.parent / "sources" / "registry.jsonl"
    source_entry = Source(
        url=youtube_url,
        title=video_info.get("title", ""),
        creator=video_info.get("uploader", video_info.get("channel", "")),
        license_type=license_type,  # type: ignore[arg-type]  # ty: ignore[invalid-argument-type]
        question_ids=[r.id for r in records],
    )
    with registry_path.open("a") as f:
        f.write(json.dumps(source_entry.model_dump()) + "\n")

    return records
